config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users
  root to: "works#index"
  get "home/index"

  resources :directors, only: [:index, :show]
  resources :works, only: [:index, :show] do
    get "higher" => "works#move_higher", as: "higher", on: :member
  end
  resources :tags, only: [:show]
  
  namespace :login do
    resources :works, only: [:new, :create, :edit, :update, :destroy]
    resources :directors, only: [:new, :create, :edit, :update, :destroy]
    resource :profile, only: [:create, :edit, :update]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  mount_uploader :image, DirectorImageUploader
  has_many :works
  validates :name, presence: true
  validates :from, presence: true
  scope :by_name, ->{ order(name: :asc) }

  before_save :capitalize_name
  def capitalize_name
    self.name = self.name.split.map(&:capitalize).join(' ')
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ProfileImageUploader
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :work_tags, dependent: :destroy
  has_many :works, through: :work_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  mount_uploader :image, WorkImageUploader
  belongs_to :director
  has_many :work_tags, dependent: :destroy
  has_many :tags, through: :work_tags

  acts_as_list

  validates :title, presence: true
  validates :release, presence: true
  validates :starring, presence: true
  validates :description, presence: true
  scope :by_new, ->{ order(updated_at: :desc) }
  scope :by_position, ->{order(position: :asc)}

  def related_works
    director.works.where.not(id: id)
  end
end

app/models/work_tag.rb
class WorkTag < ApplicationRecord
  belongs_to :work
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show]

  def index
    @directors = Director.all.by_name
  end

  # def create
  #   @director = Director.new(director_params)
  #   @director.name = @director.name.upcase
  #   @director.from = @director.from.upcase
  #
  #   if @director.save
  #     redirect_to directors_path
  #   else
  #     render "new"
  #   end
  # end

  # def new
  #   @director = Director.new
  # end

  # def edit
  # end

  def show
  end

  # def update
  #   if @director.update(director_params)
  #     redirect_to directors_path(@director)
  #   else
  #     render "edit"
  #   end
  # end

  # def destroy
  #   @director.destroy
  #   redirect_to directors_path
  # end

  private

  def set_director
    @director = Director.find(params[:id])
  end

  # def director_params
  #   params[:director].permit(:name, :from, :director_id, :position, :image)
  # end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/login/application_controller.rb
class Login::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/login/directors_controller.rb
class Login::DirectorsController < Login::ApplicationController
  before_action :set_director, only: [:edit, :update, :destroy]

  # def index
  #   @directors = Director.all.by_name
  # end

  def create
    @director = Director.new(director_params)
    @director.name = @director.name.upcase
    @director.from = @director.from.upcase

    if @director.save
      redirect_to directors_path
    else
      render "new"
    end
  end

  def new
    @director = Director.new
  end

  def edit
  end

  # def show
  # end

  def update
    if @director.update(director_params)
      redirect_to directors_path(@director)
    else
      render "edit"
    end
  end

  def destroy
    @director.destroy
    redirect_to directors_path
  end

  private

  def set_director
    @director = Director.find(params[:id])
  end

  def director_params
    params[:director].permit(:name, :from, :director_id, :position, :image)
  end


end

app/controllers/login/profiles_controller.rb
class Login::ProfilesController < Login::ApplicationController
  before_action :set_profile, only: [:edit, :update]



  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
     redirect_to edit_login_profile_path, notice: 'Your profile has been successfully saved.'
    else
     render 'edit'
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_login_profile_path, notice: 'Your profile has been successfully saved.'
    else
      render 'edit'
    end
  end

  private
  def set_profile
    @profile = current_user.profile || current_user.build_profile
  end

  def profile_params
    params.require(:profile).permit(
      :first_name,
      :last_name,
      :introduction,
      :image,
      :remove_image
    )
  end
end

app/controllers/login/works_controller.rb
class Login::WorksController < Login::ApplicationController
  before_action :set_work, only: [:edit, :update, :destroy]

  # def index
  #   @works = Work.includes(:director).by_position.page(params[:page]).per(3)
  # end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to works_path
    else
      render "new"
    end
  end

  def new
    @work = Work.new
    @work.director_id = params[:director_id] if params[:director_id].present?
  end

  def edit
  end

  # def show
  # end

  # def move_higher
  #   Work.find(params[:id]).move_higher
  #   redirect_to works_path
  # end

  def update
    if @work.update(work_params)
      redirect_to works_path(@work)
    else
      render "edit"
    end
  end

  def destroy
    @work.destroy
    redirect_to works_path
  end

  private

  def set_work
    @work = Work.find(params[:id])
  end

  def work_params
    params[:work].permit(
      :title,
      :release,
      :starring,
      :description,
      :director_id,
      :image,
      :remove_image,
      tag_ids: []
    )
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @works = @tag.works.includes(:director).by_position.page(params[:page]).per(6)
    render "works/index"
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show]

  def index
    @works = Work.includes(:director).by_position.page(params[:page]).per(6)
  end

  # def create
  #   @work = Work.new(work_params)
  #   if @work.save
  #     redirect_to works_path
  #   else
  #     render "new"
  #   end
  # end

  # def new
  #   @work = Work.new
  #   @work.director_id = params[:director_id] if params[:director_id].present?
  # end

  # def edit
  # end

  def show
  end

  def move_higher
    Work.find(params[:id]).move_higher
    redirect_to works_path
  end
    #
    # def update
    #   if @work.update(work_params)
    #     redirect_to works_path(@work)
    #   else
    #     render "edit"
    #   end
    # end
    #
    # def destroy
    #   @work.destroy
    #   redirect_to works_path
    # end
    #
  private

  def set_work
    @work = Work.find(params[:id])
  end

  # def work_params
  #   params[:work].permit(:title, :release, :starring, :description, :director_id, :image, :remove_image)
  # end
  #

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/application/_footer.html.haml
%footer.footer{:role => "contentinfo"}
  .container
    .row
      .col-sm-6
        %p.mb-1 © Copyright MyPortfolio. All Rights Reserved
        .credits
          /
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=MyPortfolio
          Designed by
          %a{:href => "https://bootstrapmade.com/"} BootstrapMade
-#       .col-sm-6.social.text-md-right
-#         %a{:href => "#"}
-#           %span.icofont-twitter
-#         %a{:href => "#"}
-#           %span.icofont-facebook
-#         %a{:href => "#"}
-#           %span.icofont-dribbble
-#         %a{:href => "#"}
-#           %span.icofont-behance
-# %a.back-to-top{:href => "#"}
-#   %i.icofont-simple-up

app/views/directors/index.html.haml
-# -@directors.each do|director|
-#
-#   ="Name："
-#   =link_to director.name, director_path(director)
-#   %br
-#   ="From："
-#   =director.from
-#   %hr
-#
-# =link_to "新規登録", new_director_path

%main#main
  / ======= Works Section =======
  %section.section.site-portfolio
    .container
      .row.mb-5.align-items-center
        .col-md-12.col-lg-6.mb-4.mb-lg-0{"data-aos" => "fade-up"}
          %h2 Director Index
          %p.mb-0 Master directors
        .col-md-12.col-lg-6.text-left.text-lg-right{"data-aos" => "fade-up", "data-aos-delay" => "100"}
          .filters
            =link_to "by Movie" , works_path
            -# %a.active{"data-filter" => "*", :href => "#"} Director
            -# %a{"data-filter" => ".web", :href => "#"} Web
            -# %a{"data-filter" => ".design", :href => "#"} Design
            -# %a{"data-filter" => ".branding", :href => "#"} Branding
            -# %a{"data-filter" => ".photography", :href => "#"} Photography
      #portfolio-grid.row.no-gutter{"data-aos" => "fade-up", "data-aos-delay" => "200"}
        -@directors.each do |director|
          .item.web.col-sm-6.col-md-4.col-lg-4.mb-4
            -# %a.item-wrap.fancybox{:href => "work_path(work)"}
            =link_to director_path(director), class: "item-wrap fancybox" do
              .work-info
                %h3=director.name
                %span=director.from
              -# %img.img-fluid{:src => "img/img_1.jpg"}/
              -if director.image.present?
                =image_tag director.image_url(:thumb), class: 'img-fluid'
              -else
                %img.img-fluid{:src => "img/default_work.png"}/

      =link_to "Add New Director",  new_login_director_path, class: "btn btn-outline-success"

app/views/directors/show.html.haml
-# =@director.name
-# =@director.from
-#
-# -@director.works.each do|work|
-#   %br
-#   =link_to "☆ #{work.title} (#{work.release.year})", work_path(work)
-#
-# %br
-# =link_to "Add New Movie", new_work_path(director_id: @director.id)
-# =link_to "編集する",  edit_director_path(@director)
-# =link_to "削除する", director_path(@director), method: :delete, data: {confirm: "本当にいいですか？"}
-# =link_to "一覧に戻る", directors_path


%main#main
  / ======= Works Section =======
  %section.section.site-portfolio
    .container
      .row.mb-5.align-items-center
        .col-md-12.col-lg-6.mb-4.mb-lg-0{"data-aos" => "fade-up"}
          %h2=@director.name
          %p.mb-0=@director.from
        .col-md-12.col-lg-6.text-left.text-lg-right{"data-aos" => "fade-up", "data-aos-delay" => "100"}
          .filters
      -if user_signed_in?
        =link_to "Add New Movie", new_login_work_path(director_id: @director.id), class: "btn btn-outline-secondary"
        =link_to "Edit",  edit_login_director_path(@director), class: "btn btn-outline-success"
        =link_to "Delete", login_director_path(@director), method: :delete, data: {confirm: "本当にいいですか？"}, class: "btn btn-outline-danger"
        -# =link_to "Back to Director Index", directors_path, class: "btn btn-secondary"
    .site-section.pb-0
      .container
        .row.align-items-stretch
          .col-md-8{"data-aos" => "fade-up"}
            -# =image_tag @director.image.to_s, class: "img-fluid"
            -if @director.image.present?
              =image_tag @director.image_url, class: "img-fluid"
              -# =image_tag work.image_url(:thumb), class: 'img-fluid'
            -else
              %img.img-fluid{:src => "/img/default_work_large.png"}/
            -# %img.img-fluid{:alt => "Image", :src => "/img/img_1_big.jpg"}/
          .col-md-3.ml-auto{"data-aos" => "fade-up", "data-aos-delay" => "100"}
            .sticky-content
              %p
              %h4.h4.mb-3 Works
              -@director.works.each do|work|
                %br
                =link_to "- #{work.title} (#{work.release.year})", work_path(work)
        %br
        =link_to "Back to Director Index", directors_path, class: "btn btn-secondary"



-# =link_to "by Title" , works_path
-# %a.active{"data-filter" => "*", :href => "#"} Director
-# %a{"data-filter" => ".web", :href => "#"} Web
-# %a{"data-filter" => ".design", :href => "#"} Design
-# %a{"data-filter" => ".branding", :href => "#"} Branding
-# %a{"data-filter" => ".photography", :href => "#"} Photography
-# #portfolio-grid.row.no-gutter{"data-aos" => "fade-up", "data-aos-delay" => "200"}
-#   -@director.works.each do|work|
-#     .item.web.col-sm-6.col-md-4.col-lg-4.mb-4
-#       -# %a.item-wrap.fancybox{:href => "work_path(work)"}
-#       =link_to work_path(work), class: "item-wrap fancybox" do
-#         .work-info
-#           %h3=work.title
-#           %span=work.release.year
-#         %img.img-fluid{:alt => "Image", :src => "/img/img_1_big.jpg"}/
-# =link_to "back", directors_path, class: "btn btn-secondary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Movie
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://fonts.googleapis.com/css?family=Inconsolata:400,700|Raleway:400,700&display=swap", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render "header"
    -# %p.notice= notice
    -# %p.alert= alert
    -if notice.present?
      .container
        %p.notice.alert.alert-success{:role => "alert"}
          =notice
    -if alert.present?
      .container
        %p.alert.alert-danger{:role => "alert"}
          =alert
    = yield
    =render "footer"

  = javascript_include_tag "application"

app/views/login/directors/_form.html.haml
=bootstrap_form_with model: [:login, @director], local: true do |f|
  =f.text_field :name
  =f.text_field :from
  =f.file_field :image
  -if @director.image?
    .m-t-5
      =image_tag @director.image_url(:thumb)
      .checkbox.checkbox-primary.m-t-5
        =f.check_box_without_bootstrap :remove_image
        =f.label :remove_image, 'Image Delete'
  =f.submit class: "btn btn-info"

app/views/login/directors/edit.html.haml
.container
  監督編集
  =render "form"

app/views/login/directors/new.html.haml
.container
  新規登録
  =render "form"

app/views/login/profiles/edit.html.haml
%main#main
  .site-section.pb-0.site-portfolio
    .container
      .row.mb-5.align-items-end
        .col-md-12{"data-aos" => "fade-up"}
          %h2 Profile
          %p.mb-0
            Introduce yourself and let's introduce great movies with us!
      .row
        .col-md-12.mb-5.mb-md-0{"data-aos" => "fade-up"}
          =bootstrap_form_with model: [:login, @profile], url: login_profile_path, local: true do |f|
            .row
              .col-md-6
                =f.text_field :first_name
              .col-md-6
                =f.text_field :last_name
              .col-md-12
                =f.text_area :introduction
              .col-md-12.mb-3
                =f.file_field :image
                =f.hidden_field :image_cache
                -if @profile.image?
                  .js-image-preview.m-t-5
                    =image_tag @profile.image_url(:thumb)
                    .checkbox.checkbox-primary.m-t-5
                      =f.check_box_without_bootstrap :remove_image
                      =f.label :remove_image, 'Image Delete'
                =f.submit 'Save profile', class: "readmore d-block w-100"

app/views/login/works/edit.html.haml
.container
  作品編集
  =render "form"

app/views/works/index.html.haml
%main#main
  / ======= Works Section =======
  %section.section.site-portfolio
    .container
      .row.mb-5.align-items-center
        .col-md-12.col-lg-6.mb-4.mb-lg-0{"data-aos" => "fade-up"}
          %h2 Movie Index
          %p.mb-0 Masterpieces
          =link_to "New Movie",  new_login_work_path, class: "btn btn-outline-success"
        .col-md-12.col-lg-6.text-left.text-lg-right{"data-aos" => "fade-up", "data-aos-delay" => "100"}
          .filters
            =link_to "by Director" , directors_path
            -# %a.active{"data-filter" => "*", :href => "#"} Director
            -# %a{"data-filter" => ".web", :href => "#"} Web
            -# %a{"data-filter" => ".design", :href => "#"} Design
            -# %a{"data-filter" => ".branding", :href => "#"} Branding
            -# %a{"data-filter" => ".photography", :href => "#"} Photography
      #portfolio-grid.row.no-gutter{"data-aos" => "fade-up", "data-aos-delay" => "200"}
        -@works.each do |work|
          .item.web.col-sm-6.col-md-4.col-lg-4.mb-4
            -# %a.item-wrap.fancybox{:href => "work_path(work)"}
            =link_to work_path(work), class: "item-wrap fancybox" do
              .work-info
                %h3=work.title
                %span=work.release.year
                %br
                %span=work.director.name
              -if work.image.present?
                =image_tag work.image_url(:thumb), class: 'img-fluid'
              -else
                %img.img-fluid{:src => "img/default_work.png"}/
              -# =image_tag work.image_url(:thumb), class: "img-fluid"
              -# %img.img-fluid{:src => "img/img_1.jpg"}/
      =paginate @works

-#   / End  Works Section
-#   / ======= Clients Section =======
-#   %section.section
-#     .container
-#       .row.justify-content-center.text-center.mb-4
-#         .col-5
-#           %h3.h3.heading My Clients
-#           %p Lorem ipsum dolor sit amet consectetur adipisicing elit explicabo inventore.
-#       .row
-#         .col-4.col-sm-4.col-md-2
-#           %a.client-logo{:href => "#"}
-#             %img.img-fluid{:alt => "Image", :src => "img/logo-adobe.png"}/
-#         .col-4.col-sm-4.col-md-2
-#           %a.client-logo{:href => "#"}
-#             %img.img-fluid{:alt => "Image", :src => "img/logo-uber.png"}/
-#         .col-4.col-sm-4.col-md-2
-#           %a.client-logo{:href => "#"}
-#             %img.img-fluid{:alt => "Image", :src => "img/logo-apple.png"}/
-#         .col-4.col-sm-4.col-md-2
-#           %a.client-logo{:href => "#"}
-#             %img.img-fluid{:alt => "Image", :src => "img/logo-netflix.png"}/
-#         .col-4.col-sm-4.col-md-2
-#           %a.client-logo{:href => "#"}
-#             %img.img-fluid{:alt => "Image", :src => "img/logo-nike.png"}/
-#         .col-4.col-sm-4.col-md-2
-#           %a.client-logo{:href => "#"}
-#             %img.img-fluid{:alt => "Image", :src => "img/logo-google.png"}/
-#   / End Clients Section
-#   / ======= Services Section =======
-#   %section.section
-#     .container
-#       .row.justify-content-center.text-center.mb-4
-#         .col-5
-#           %h3.h3.heading My Services
-#           %p Lorem ipsum dolor sit amet consectetur adipisicing elit explicabo inventore.
-#       .row
-#         .col-12.col-sm-6.col-md-6.col-lg-3
-#           %span.la.la-cube.la-3x.mb-4
-#           %h4.h4.mb-2 Web Design
-#           %p Lorem ipsum dolor sit amet consectetur adipisicing elit explicabo inventore.
-#           %ul.list-unstyled.list-line
-#             %li Lorem ipsum dolor sit amet consectetur adipisicing
-#             %li Non pariatur nisi
-#             %li Magnam soluta quod
-#             %li Lorem ipsum dolor
-#             %li Cumque quae aliquam
-#         .col-12.col-sm-6.col-md-6.col-lg-3
-#           %span.la.la-mobile.la-3x.mb-4
-#           %h4.h4.mb-2 Mobile Applications
-#           %p Lorem ipsum dolor sit amet consectetur adipisicing elit explicabo inventore.
-#           %ul.list-unstyled.list-line
-#             %li Lorem ipsum dolor sit amet consectetur adipisicing
-#             %li Non pariatur nisi
-#             %li Magnam soluta quod
-#             %li Lorem ipsum dolor
-#             %li Cumque quae aliquam
-#         .col-12.col-sm-6.col-md-6.col-lg-3
-#           %span.la.la-image.la-3x.mb-4
-#           %h4.h4.mb-2 Graphic Design
-#           %p Lorem ipsum dolor sit amet consectetur adipisicing elit explicabo inventore.
-#           %ul.list-unstyled.list-line
-#             %li Lorem ipsum dolor sit amet consectetur adipisicing
-#             %li Non pariatur nisi
-#             %li Magnam soluta quod
-#             %li Lorem ipsum dolor
-#             %li Cumque quae aliquam
-#         .col-12.col-sm-6.col-md-6.col-lg-3
-#           %span.la.la-search.la-3x.mb-4
-#           %h4.h4.mb-2 SEO
-#           %p Lorem ipsum dolor sit amet consectetur adipisicing elit explicabo inventore.
-#           %ul.list-unstyled.list-line
-#             %li Lorem ipsum dolor sit amet consectetur adipisicing
-#             %li Non pariatur nisi
-#             %li Magnam soluta quod
-#             %li Lorem ipsum dolor
-#             %li Cumque quae aliquam
-#   / End Services Section
-#   / ======= Testimonials Section =======
-#   %section.section.pt-0
-#     .container
-#       .owl-carousel.testimonial-carousel
-#         .testimonial-wrap
-#           .testimonial
-#             %img.img-fluid{:alt => "Image", :src => "img/person_1.jpg"}/
-#             %blockquote
-#               %p
-#                 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus incidunt ut officiis
-#                 explicabo inventore.
-#             %p — Jean Hicks
-#         .testimonial-wrap
-#           .testimonial
-#             %img.img-fluid{:alt => "Image", :src => "img/person_2.jpg"}/
-#             %blockquote
-#               %p
-#                 Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam necessitatibus incidunt ut officiis
-#                 explicabo inventore.
-#             %p — Chris Stanworth
-#   / End Testimonials Section
-# / End #main
-# / ======= Footer =======

app/views/works/show.html.haml
-# =@work.title
-# =@work.release
-# =@work.starring
-# =@work.description
-# %br
-# =link_to "#{@work.director.name}", director_path(@work.director)
-# %br
-# %br
-# ="#{@work.director.name} Works"
-# %br
-# -@work.related_works.each do|work|
-#   =link_to "#{work.title} (#{work.release.year})", work_path(work)
-#   %br
-# %br
-# =link_to "一覧に戻る", works_path
-# =link_to "編集する",  edit_work_path(@work)
-# =link_to "削除する", work_path(@work), method: :delete, data: {confirm: "本当にいいですか？"}

%main#main
  %section.section
    .container
      .row.mb-4.align-items-center
        .col-md-6{"data-aos" => "fade-up"}
          %h2=@work.title
          %p
            Release:#{@work.release.year}
            %br
            Director:
            =link_to @work.director.name, director_path(@work.director)
          -if @work.tags.present?
            -@work.tags.each do|tag|
              =link_to tag.name, tag_path(tag), class: "badge badge-secondary"
      -if user_signed_in?
        =link_to "Edit",  edit_login_work_path(@work), class: "btn btn-outline-success"
        =link_to "Delete", login_work_path, method: :delete, data: {confirm: "本当にいいですか？"}, class: "btn btn-outline-danger"

    .site-section.pb-0
      .container
        .row.align-items-stretch
          .col-md-8{"data-aos" => "fade-up"}
            -if @work.image.present?
              =image_tag @work.image_url, class: "img-fluid"
              -# =image_tag work.image_url(:thumb), class: 'img-fluid'
            -else
              %img.img-fluid{:src => "/img/default_work_large.png"}/
            -# =image_tag @work.image_url, class: "img-fluid"
            -# %img.img-fluid{:alt => "Image", :src => "/img/img_1_big.jpg"}/
          .col-md-3.ml-auto{"data-aos" => "fade-up", "data-aos-delay" => "100"}
            .sticky-content
              %h3.h3=@work.title
              %p.mb-4
                %span.text-muted=@work.release.year
              .mb-5
                %p
                  =@work.description
              %h4.h4.mb-3 Director
              %ul.list-unstyled.list-line.mb-5
                %li=link_to @work.director.name, director_path(@work.director)

    -if @work.related_works.present?
      .site-section.pb-0
        .container
          .row.justify-content-center.text-center.mb-4
            .col-5
              %h3.h3.heading="#{@work.director.name} Works"
              %p Also recommend these works
          .row{"data-aos" => "fade-up", "data-aos-delay" => "200"}
            -@work.related_works.each do|work|
              .item.web.col-sm-6.col-md-4.col-lg-4.mb-4
                -# %a.item-wrap.fancybox{:href => "work_path(work)"}
                =link_to work_path(work), class: "item-wrap fancybox" do
                  .work-info
                    %h3=work.title
                    %span=work.release.year
                  -if work.image.present?
                    =image_tag work.image_url(:thumb), class: 'img-fluid'
                  -else
                    %img.img-fluid{:src => "/img/default_work.png"}/


            -# .row{"data-aos" => "fade-up", "data-aos-delay" => "200"}
            -#   .item.web.col-sm-6.col-md-4.col-lg-4.mb-4
            -#     %a.item-wrap.fancybox{:href => "work-single.html"}
            -#       .work-info
            -#         %h3 Boxed Water
            -#         %span Web
            -#       %img.img-fluid{:src => "img/img_1.jpg"}/
            -#   .item.photography.col-sm-6.col-md-4.col-lg-4.mb-4
            -#     %a.item-wrap.fancybox{:href => "work-single.html"}
            -#       .work-info
            -#         %h3 Build Indoo
            -#         %span Photography
            -#       %img.img-fluid{:src => "img/img_2.jpg"}/
            -#   .item.branding.col-sm-6.col-md-4.col-lg-4.mb-4
            -#     %a.item-wrap.fancybox{:href => "work-single.html"}
            -#       .work-info
            -#         %h3 Cocooil
            -#         %span Branding
            -#       %img.img-fluid{:src => "img/img_3.jpg"}/
            -#   .item.design.col-sm-6.col-md-4.col-lg-4.mb-4
            -#     %a.item-wrap.fancybox{:href => "work-single.html"}
            -#       .work-info
            -#         %h3 Nike Shoe
            -#         %span Design
            -#       %img.img-fluid{:src => "img/img_4.jpg"}/
            -#   .item.photography.col-sm-6.col-md-4.col-lg-4.mb-4
            -#     %a.item-wrap.fancybox{:href => "work-single.html"}
            -#       .work-info
            -#         %h3 Kitchen Sink
            -#         %span Photography
            -#       %img.img-fluid{:src => "img/img_5.jpg"}/
            -#   .item.branding.col-sm-6.col-md-4.col-lg-4.mb-4
            -#     %a.item-wrap.fancybox{:href => "work-single.html"}
            -#       .work-info
            -#         %h3 Amazon
            -#         %span brandingn
            -#       %img.img-fluid{:src => "img/img_6.jpg"}/